import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar"
import { Navbar } from "@/components/Navbar/Navbar"
import { CustomSidebarTrigger } from "@/components/ui/CustomSidebarTrigger"
 
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <SidebarProvider>

          {/* Barra de navegación */}
          <Navbar />
          
          {/*Boton Colapsar-Expandir - Configuración personalizable */}
          <CustomSidebarTrigger 
            top="2rem"          // Posición vertical desde arriba
            // bottom="2rem"    // Alternativa: posición desde abajo
            marginHorizontal={16} // Separación del sidebar (16px)
            size="sm"            // Tamaño: "sm", "md", "lg"
            iconSize="h-4 w-4"   // Tamaño del ícono
          />

          {/* Contenido principal */}
          <main className="min-h-screen w-full transition-all duration-300">
            <div className="container mx-auto px-4 py-6 md:px-6 lg:px-8">
              {children}
            </div>
          </main>

        </SidebarProvider>
      </body>
    </html>
  );
}
